## Homework 5

<!--
Set the working directory.
No Rchunk is needed to accomplish this.
-->



<!--
Read in the homework5.csv data. For each of the following steps you
should preface your R commands with some plain English explanation.
The data are fabricated and include the number of words per minute
that people can type when listening to no music and when listening
to heavy metal.
-->
```{r}
dat<-read.csv("homework5.csv")
```


<!--
Check the structure of the data.
-->

```{r}
str(dat)
```

<!--
Find the mean words per minute for the two groups.
-->
```{r}
mean(dat$wpm[dat$music=="metal"])
mean(dat$wpm[dat$music=="none"])
```


<!--
Run an independent t-test to determine if the mean wpm for the
no music group is different from the mean wpm from heavy metal
group. Interpret the results of your analysis after you run it.
-->
```{r}
t.test(dat$wpm[dat$music=="metal"],dat$wpm[dat$music=="none"],var.equal=TRUE)
```

<!--
Run another independent t-test with the alternative hypothesis that
the heavy metal group types faster than the no music group. Interpret
the results of your analyses.
-->

```{r}
t.test(dat$wpm[dat$music=="metal"],dat$wpm[dat$music=="none"],var.equal=TRUE, alternative = "greater")
```


<!--
Create a bar graph of the data.
-->



<!--
Conduct and interpret a two-tailed paired t-test on the data.
-->
```{r}
t.test(dat$wpm[dat$music=="metal"],
        dat$wpm[dat$music=="none"],
        var.equal=TRUE,
        paired=TRUE)
```
